// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Définitions',
      items: [
        'definitions/index',
        'definitions/sharepoint',
        'definitions/powerautomate',
      ],
    },
    {
      type: 'category',
      label: 'Je suis un TI',
      items: [
        {
          type: 'category',
          label: 'Site web',
          items: [
            'Je suis un TI/site-web/catego',
          ]
        },
        {
          type: 'category',
          label: 'testing EP',
          items: [
            'Je suis un TI/testing EP/introduction',
            'Je suis un TI/testing EP/documents',
            {
              type: 'category',
              label: 'Pages',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'Je suis un TI/testing EP/pages',
                },
              ],
            },
            {
              type: 'category',
              label: 'List Forms',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'Je suis un TI/testing EP/list-forms',
                },
              ],
            },
            {
              type: 'category',
              label: 'Flows',
              items: [
                'flows/onboarding',
                'flows/offboarding',
                'flows/embauche',
              ],
            },
            'Je suis un TI/testing EP/maintenance',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Je suis un employé',
      items: [
        'employé/index',
        {
          type: 'category',
          label: "Site web",
          items: [
            'employé/site-web/catego',
          ]
        },
        {
          type: 'category',
          label: 'Formulaires',
          items: [
            'employé/formulaires/onboarding',
            'employé/formulaires/offboarding',
            'employé/formulaires/embauche',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
