// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Définitions',
      items: [
        'definitions/index',
        'definitions/sharepoint',
        'definitions/powerautomate',
      ],
    },
    {
      type: 'category',
      label: 'testing EP 2',
      items: [
        'introduction',
        'documents',
        {
          type: 'category',
          label: 'Pages',
          items: [
            {
              type: 'autogenerated',
              dirName: 'pages',
            },
          ],
        },
        {
          type: 'category',
          label: 'List Forms',
          items: [
            {
              type: 'autogenerated',
              dirName: 'list-forms',
            },
          ],
        },
        {
          type: 'category',
          label: 'Flows',
          items: [
            'flows/onboarding',
            'flows/offboarding',
            'flows/embauche',
          ],
        },
        'maintenance',
      ],
    },
    {
      type: 'category',
      label: 'Je suis un employé',
      items: [
        'employé/index',
        {
          type: 'category',
          label: "Site web",
          items: [
            'employé/site-web/catego.ptranet.com',
          ]
        },
        {
          type: 'category',
          label: 'Formulaires',
          items: [
            'employé/formulaires/onboarding',
            'employé/formulaires/offboarding',
            'employé/formulaires/embauche',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
